-- 사용자
CREATE TABLE worker (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 채팅방

CREATE TABLE room (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255),
    ai_system VARCHAR(10000),
    ai_proactive_next_date TIMESTAMP,
    last_read_chat_id INT UNSIGNED,
    is_deleted BOOLEAN DEFAULT 0 NOT NULL,
    creator_id INT UNSIGNED NOT NULL,
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (creator_id) REFERENCES worker(id),
    FOREIGN KEY (last_read_chat_id) REFERENCES chat(id)
);

-- 채팅

CREATE TABLE chat (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    content TEXT,
    room_id INT UNSIGNED NOT NULL,
    creator_id INT UNSIGNED NOT NULL,
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (room_id) REFERENCES room(id),
    FOREIGN KEY (creator_id) REFERENCES worker(id)
);

-- 푸시 알림

CREATE TABLE push_subscription (
    user_id INT UNSIGNED NOT NULL,
    endpoint TEXT NOT NULL UNIQUE,
    p256dh TEXT NOT NULL,
    auth TEXT NOT NULL,
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES worker(id)
);

-- 디폴트 값
INSERT INTO worker VALUES(1, "ai@admin.net", "$2a$10$KFvdVE9pibU.K6efgccCHuVOrvGTIzoD9Uxt5tzR/zRxjIIr6s3cy", "2026-03-19","2026-03-19")